### ISSUE TITLE
TypeError: Cannot convert module.initialBlock to a BigInt

### ISSUE THREAD

**Issue by keisuke-kanao** [substreams-js/substreams-js#38]
https://github.com/substreams-js/substreams-js/blob/main/packages/core/src/manifest/signature/create-module-hash.ts#L79
```
  new DataView(array.buffer).setBigUint64(0, module.initialBlock, true);
````
For Node.js v18.18.0, this line may raise TypeError, such as `Cannot convert 0 to a BigInt, should be:
```
  new DataView(array.buffer).setBigUint64(0, BigInt(module.initialBlock), true);
\
```

**Comment by fubhy** [comment]
This should already be a bigint at this point.

**Comment by keisuke-kanao** [comment]
In fact, when I ran https://github.com/pinax-network/substreams-sink/blob/main/example.js from https://github.com/pinax-network/substreams-sink, I got an error.
Please note that the actual path is modified to `path-to-pinax-network` in the below.
```$  git clone https://github.com/pinax-network/substreams-sink.git
$  cd substreams-sink
$  npm install
$ npm run build
$ node example.js run -e https://eos.firehose.eosnation.io:9001 --manifest /path-to-pinax-network/substreams/eosio.token/substreams.yaml --module-name map_transfers -s 12292922 -t 12292923

(node:41320) ExperimentalWarning: Import assertions are not a stable feature of the JavaScript language. Avoid relying on their current behavior and syntax as those might change in a future version of Node.js.
(Use `node --trace-warnings ...` to show where the warning was created)
(node:41320) ExperimentalWarning: Importing JSON modules is an experimental feature and might change at any time
file:///path-to-pinax-network/substreams-sink/node_modules/@substreams/core/dist/manifest/signature/create-module-hash.js:44
    new DataView(array.buffer).setBigUint64(0, module.initialBlock, true);
                               ^

TypeError: Cannot convert 0 to a BigInt
    at DataView.setBigUint64 (<anonymous>)
    at encodeInitialBlock (file:///path-to-pinax-network/substreams-sink/node_modules/@substreams/core/dist/manifest/signature/create-module-hash.js:44:32)
    at createModuleHash (file:///path-to-pinax-network/substreams-sink/node_modules/@substreams/core/dist/manifest/signature/create-module-hash.js:13:17)
    at createModuleHashHex (file:///path-to-pinax-network/substreams-sink/node_modules/@substreams/core/dist/manifest/signature/create-module-hash.js:6:24)
    at setup (file:///path-to-pinax-network/substreams-sink/dist/src/setup.js:61:30)
    at async Command.<anonymous> (file:///path-to-pinax-network/substreams-sink/example.js:14:23)

Node.js v18.18.0
```
It this case, is it caller's responsibility to set `BigInt(0)` vaue?

**Comment by fubhy** [comment]
Hmm no but the parser should turn it into a bigint. If not thats a bug. Will look into it!

**Comment by fubhy** [comment]
Can you check if @substreams/core@0.5.0 fixes it?

**Comment by keisuke-kanao** [comment]
I replaced `@substreams/core` with `@substreams/core@0.5.0`, but still got the same error.
Previously `@substreams/core@0.1.19` was installed.

**Comment by fubhy** [comment]
You need to update all packages.

**Comment by fubhy** [comment]
I just confirmed that it works with all packages updated to their latest versions ./cc @DenisCarriere

**Comment by keisuke-kanao** [comment]
I confirmed too. 
I will close the issue.
