### ISSUE TITLE
custom eth rpc node

### ISSUE THREAD

**Issue by Dreamerryao** [substreams-js/substreams-js#57]
Hi team, when i use substream to fetch uniswap data, i always get this error.

``` 
This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
ConnectError: [unknown] terminated

  at Function.from (file:////@bufbuild+connect@0.13.0_@bufbuild+protobuf@1.7.2/node_modules/@bufbuild/connect/dist/esm/connect-error.js:72:20)
   at abort (file:///@bufbuild+connect@0.13.0_@bufbuild+protobuf@1.7.2/node_modules/@bufbuild/connect/dist/esm/protocol/run-call.js:103:36)
```

I think it happens because `eth_call` connect error. 
So can I use my custom rpc node ?

**Comment by fubhy** [comment]
Hey @Dreamerryao. I'm confused ... substreams-js does not do any `eth_calls`. That's all done by the substream runtime behind the scenes. You are not connecting to any rpc nodes here. We are just consuming output from the substream server here in `substreams-js` land.
